hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
metafile = true

[[files]]
file = "mods/ae2-lightning-tech.pw.toml"
metafile = true

[[files]]
file = "mods/ae2-tangible-bookmarks.pw.toml"
metafile = true

[[files]]
file = "mods/ae2-wcwt.pw.toml"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/aero-player-tilt.pw.toml"
metafile = true

[[files]]
file = "mods/aero_cam_sync.pw.toml"
metafile = true

[[files]]
file = "mods/aeroengine.pw.toml"
metafile = true

[[files]]
file = "mods/aeronautics-wind-sound.pw.toml"
metafile = true

[[files]]
file = "mods/aeronauticsvoidseas.pw.toml"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
metafile = true

[[files]]
file = "mods/always-shield.pw.toml"
metafile = true

[[files]]
file = "mods/amplified-nether.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "mods/applied-experienced.pw.toml"
metafile = true

[[files]]
file = "mods/applied-schematics.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
metafile = true

[[files]]
file = "mods/baguettelib.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/bedrockstuff.pw.toml"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
metafile = true

[[files]]
file = "mods/biolith.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-neoforge.pw.toml"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/configurable.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
metafile = true

[[files]]
file = "mods/corpse-x-curios-api-compat.pw.toml"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
metafile = true

[[files]]
file = "mods/create-aero-radars.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-boat-propellers.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-climbable-rope.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-encased-fluid-pipes.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-lift-patch.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-offroad-addon-stickywheels.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-paddlewheels.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-throwable-rope-connector.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-toolgun.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-transmission-linkage.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-vapor-trails.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics.pw.toml"
metafile = true

[[files]]
file = "mods/create-aerowarptics.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeroworks.pw.toml"
metafile = true

[[files]]
file = "mods/create-ballast.pw.toml"
metafile = true

[[files]]
file = "mods/create-bettersaw.pw.toml"
metafile = true

[[files]]
file = "mods/create-big-cannons-advanced-technologies.pw.toml"
metafile = true

[[files]]
file = "mods/create-big-cannons-going-ballistic.pw.toml"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
metafile = true

[[files]]
file = "mods/create-blaze-burner-fuels.pw.toml"
metafile = true

[[files]]
file = "mods/create-cardboarded-conveynience.pw.toml"
metafile = true

[[files]]
file = "mods/create-cobblestone-deepslate-generators.pw.toml"
metafile = true

[[files]]
file = "mods/create-cobblestone.pw.toml"
metafile = true

[[files]]
file = "mods/create-copper-zinc.pw.toml"
metafile = true

[[files]]
file = "mods/create-curios-jetpack.pw.toml"
metafile = true

[[files]]
file = "mods/create-deep-seas.pw.toml"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
metafile = true

[[files]]
file = "mods/create-drill-levitite.pw.toml"
metafile = true

[[files]]
file = "mods/create-dynamic-lights.pw.toml"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
metafile = true

[[files]]
file = "mods/create-grappling-hooks.pw.toml"
metafile = true

[[files]]
file = "mods/create-horse-decimation.pw.toml"
metafile = true

[[files]]
file = "mods/create-jetpack.pw.toml"
metafile = true

[[files]]
file = "mods/create-meta-logistics.pw.toml"
metafile = true

[[files]]
file = "mods/create-mobile-packages.pw.toml"
metafile = true

[[files]]
file = "mods/create-package.pw.toml"
metafile = true

[[files]]
file = "mods/create-power-chip.pw.toml"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
metafile = true

[[files]]
file = "mods/create-propulsion-simulated.pw.toml"
metafile = true

[[files]]
file = "mods/create-radars.pw.toml"
metafile = true

[[files]]
file = "mods/create-ranged.pw.toml"
metafile = true

[[files]]
file = "mods/create-renewable-diamonds.pw.toml"
metafile = true

[[files]]
file = "mods/create-renewable-egapples.pw.toml"
metafile = true

[[files]]
file = "mods/create-renewable-netherite.pw.toml"
metafile = true

[[files]]
file = "mods/create-rns.pw.toml"
metafile = true

[[files]]
file = "mods/create-sable-dynamic-lights.pw.toml"
metafile = true

[[files]]
file = "mods/create-simple-ore-doubling.pw.toml"
metafile = true

[[files]]
file = "mods/create-simulated-additions.pw.toml"
metafile = true

[[files]]
file = "mods/create-smog.pw.toml"
metafile = true

[[files]]
file = "mods/create-stones.pw.toml"
metafile = true

[[files]]
file = "mods/create-threaded-trains.pw.toml"
metafile = true

[[files]]
file = "mods/create-towed.pw.toml"
metafile = true

[[files]]
file = "mods/create-tracks+.pw.toml"
metafile = true

[[files]]
file = "mods/create-transmission!.pw.toml"
metafile = true

[[files]]
file = "mods/create-useful-flint.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/createnuclear.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/data-anchor.pw.toml"
metafile = true

[[files]]
file = "mods/deployer.pw.toml"
metafile = true

[[files]]
file = "mods/disconnect-packet-fix.pw.toml"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/distraction-free-recipes.pw.toml"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
metafile = true

[[files]]
file = "mods/dodospyglass-spyglass-curios-compat.pw.toml"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
metafile = true

[[files]]
file = "mods/emi-create-schematics.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi-ores.pw.toml"
metafile = true

[[files]]
file = "mods/emi-swift-copy.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/experiencelib.pw.toml"
metafile = true

[[files]]
file = "mods/extended-ae.pw.toml"
metafile = true

[[files]]
file = "mods/extra-gauges.pw.toml"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/fastsuite.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/fixed-anvil-repair-cost.pw.toml"
metafile = true

[[files]]
file = "mods/flw-vanillin.pw.toml"
metafile = true

[[files]]
file = "mods/fokusapi.pw.toml"
metafile = true

[[files]]
file = "mods/forgeendertech.pw.toml"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/forgiving-void.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/glodium.pw.toml"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
metafile = true

[[files]]
file = "mods/hots-aerostuff.pw.toml"
metafile = true

[[files]]
file = "mods/hypertube.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/json-things.pw.toml"
metafile = true

[[files]]
file = "mods/jupiter.pw.toml"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/large-ore-deposits.pw.toml"
metafile = true

[[files]]
file = "mods/ldlib.pw.toml"
metafile = true

[[files]]
file = "mods/lever-drugster.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lithosphere.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/llo.pw.toml"
metafile = true

[[files]]
file = "mods/lodestone-update-backport.pw.toml"
metafile = true

[[files]]
file = "mods/logical-iframes.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/map-atlases-forge.pw.toml"
metafile = true

[[files]]
file = "mods/markdownmanual.pw.toml"
metafile = true

[[files]]
file = "mods/mixintrace-reforged.pw.toml"
metafile = true

[[files]]
file = "mods/modern-minecarts.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/multiple-dragon-eggs.pw.toml"
metafile = true

[[files]]
file = "mods/myotus-lib.pw.toml"
metafile = true

[[files]]
file = "mods/neoecoae.pw.toml"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
metafile = true

[[files]]
file = "mods/notenoughrecipebook.pw.toml"
metafile = true

[[files]]
file = "mods/ocean-lily-pad-village.pw.toml"
metafile = true

[[files]]
file = "mods/overflowing-bars.pw.toml"
metafile = true

[[files]]
file = "mods/packagerspsic.pw.toml"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/power-grid.pw.toml"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
metafile = true

[[files]]
file = "mods/protection-pixel.pw.toml"
metafile = true

[[files]]
file = "mods/pulsetech.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/room-for-two.pw.toml"
metafile = true

[[files]]
file = "mods/rpl.pw.toml"
metafile = true

[[files]]
file = "mods/sable-true-impact.pw.toml"
metafile = true

[[files]]
file = "mods/sable.pw.toml"
metafile = true

[[files]]
file = "mods/sablecompat.pw.toml"
metafile = true

[[files]]
file = "mods/sea-creeps.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/seeu.pw.toml"
metafile = true

[[files]]
file = "mods/shatterbyte-lib.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/sky-void-additions.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-aeronautics.pw.toml"
metafile = true

[[files]]
file = "mods/ssrd.pw.toml"
metafile = true

[[files]]
file = "mods/thunderbolt-core.pw.toml"
metafile = true

[[files]]
file = "mods/tis3d.pw.toml"
metafile = true

[[files]]
file = "mods/txnilib.pw.toml"
metafile = true

[[files]]
file = "mods/unseaworthy.pw.toml"
metafile = true

[[files]]
file = "mods/vestalihy.pw.toml"
metafile = true

[[files]]
file = "mods/voidfog.pw.toml"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yeetus-experimentus.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-caves.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/drodi-extendo-grip.pw.toml"
metafile = true

[[files]]
file = "servers.dat"

[[files]]
file = "thingpacks/horse_breeding/data/horse_breeding/recipe/mixing/forbidden_breeding.json"

[[files]]
file = "thingpacks/horse_breeding/pack.mcmeta"

[[files]]
file = "thingpacks/recipe_disabling/data/ae2/recipe/network/blocks/crank.json"

[[files]]
file = "thingpacks/recipe_disabling/data/ae2/recipe/network/blocks/energy_vibration_chamber.json"

[[files]]
file = "thingpacks/recipe_disabling/pack.mcmeta"

[[files]]
file = "unsup.ini"

[[files]]
file = "unsup.toml"
