name = "Aeronautics"
author = "P1x3l101"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04bf96f2c39800f7d8c634c7c6e855d3db3e97ca2e7ee82022e7dcc754be7ea9"

[versions]
lwjgl3 = "3.3.3"
minecraft = "1.21.1"
neoforge = "21.1.228"
unsup = "1.1.5"
