name = "Aeronautics"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77ba1997a46a58e2cc013ad089f85b46b26f5967081359ec10aca81c4162ab0d"

[versions]
lwjgl3 = "3.3.3"
minecraft = "1.21.1"
neoforge = "21.1.228"
unsup = "1.1.5"
