#Maximum number of times the Console or Processor can unwrap macros in a single evaluation. Higher values mean more complex programs are possible, but may cause lag spikes when the macro is evaluated. [Default: 256]
# Default: 256
# Range: 4 ~ 512
maxMacroUnwrapCount = 256
#Maximum range of the Coil Cannon in blocks. [Default: 25]
# Default: 25
# Range: 1 ~ 64
cannonMaxRange = 25
#The Coil Cannon can break blocks with below this blast resistance. [Default: 50]
# Default: 50
# Range: > 1
cannonMaxBlastResist = 50
#Maximum range of the Orb Projector in blocks. [Default: 32]
# Default: 32
# Range: 1 ~ 64
orbProjectorMaxRange = 32
#A list of entities the Orb can never pick up. [Default: "minecraft:ender_dragon", "minecraft:wither", "minecraft:warden"]
orbCannotGrab = ["minecraft:ender_dragon", "minecraft:wither", "minecraft:warden"]
#How far the Orb moves each movement tick in blocks. [Default: 0.12]
# Default: 0.12
# Range: 0.01 ~ 1.0
orbSpeed = 0.12
#The range of detection for the Scanner has a radius of this many blocks. [Default: 16]
# Default: 16
# Range: 4 ~ 64
scannerRange = 32
#How many ticks the Retriever rests between moving items while open. [Default: 3]
# Default: 3
# Range: 1 ~ 20
itemFlowInterval = 3
#The maximum distance in blocks that the Remote Console works over. The target block must still be loaded no matter the range. Set to 0 to disable range checking entirely. [Default: 64]
# Default: 64
# Range: 0 ~ 512
remoteConsoleRange = 64
