#Timing Settings (20 ticks = 1 second)
[timing]
	#Base time in ticks before fire spreads to neighbors
	# Default: 40
	# Range: 10 ~ 200
	spreadDelay = 40
	#Base time in ticks before a block turns to dirt
	# Default: 80
	# Range: 20 ~ 300
	burnTime = 80
	#Max time in ticks before fire goes out after a block converts to dirt
	# Default: 20
	# Range: 0 ~ 60
	extinguishTime = 20

#Spread Direction
[spread]
	#Allow fire to spread to burnable blocks one level higher (hills)
	spreadUphill = true
	#Allow fire to spread to burnable blocks one level lower (hills)
	spreadDownhill = true
